### ISSUE TITLE
'undefined' values

### ISSUE THREAD

**Issue by harphere** [notmayo/ecobee-card#1]
Hi, I just started noticing the following 'undefined' items which is the heating/cooling logo on the top and the slider on the right side: 

![image](https://user-images.githubusercontent.com/28116390/205136987-f2077248-8fe6-48e8-83ef-0947fe6b276c.png)

Is this something you can look into? I'm running Home Assistant 2022.11.5 with Frontend 20221108.0 - latest

Thanks!

**Comment by notmayo** [comment]
Hello, are you still having this issue? I have tried to reproduce and I am unable. I have tried installing in a test environment (new install) on the latest home assistant versions and cannot reproduce your error. Have you refreshed your browser/cache after installation?

**Comment by harphere** [comment]
Hi, I'm not having it the last couple of times I checked. I think it may have something to do with my Ecobee rebooting (an entirely separate issue) at or around the same time I'm checking the card in Lovelace. Apologies for keeping this open for so long, closing it now. Thanks!
